src/components/tasks/card/card.module.scss
=> issue/95- box-shadow added for task card

src/components/Accordion/Accordion.module.scss, src/styles/tasks.module.scss
parent - task_container.
fix #93 
On changing the maximum width to 750px it will look like this : 
After aligning to center it looks better, so updating with the same
Do comment with the same incase of any issues
=> issue/93 - Accordion width updated and centered in the parent

src/components/navBar/navBar.module.scss
closes #213 
iPhone X view before changes:
iPhone X view after changes:
Samsung Galaxy fold view before changes:
Samsung Galaxy fold view after changes:
Note:
The rest of the devices were aligned as expected.
Fix for all screens to vertically centre the text.
Before changes:
After changes:
=> fix for navBar style in mobile devices

src/components/idleMembers/card/index.tsx
RFC - #304
Whenever there is an error in getting the image of a user on the `idle-members` page it used to re-fetch infinitely as the error handling was done in a `non-React way` and therefore was not working.
I just simply added a state to the component so that If It finds any error, it will re-render with a fetching fallback image for error handling.
=> Infinite Image fetch fixed

.env.development, src/components/tasks/card/TaskTagEdit.tsx, src/components/tasks/card/card.module.scss, src/components/tasks/card/index.tsx, src/context/tasks.context.tsx, src/interfaces/level.type.ts, src/interfaces/taskItem.type.ts
- Refactoring the level and item keys
- Filtering out tag options if it's already present on the task (In edit mode of tasks page on status site)
Fig: System design is not present in the below options as it was already present on the task.
=> refactoring and filtering options in edit mode

.env.development, src/pages/mine.tsx
This PR fixes issue https://github.com/Real-Dev-Squad/website-status/issues/375
There were two issues .
1) The Mine component was re evaluating in a loop as the useEffect hook had "response" as  dependency.
2)  The if condition to check if there is a response with length had a not condition which did the opposite. Ex - for 0 results found !0 would evaluate to 1 and !1 would evaluate to a falsy value due to which the setTasks state updating function was not getting executed.
Fixes I have done -
1) Removed response as a dependency as we only want to call the API once when the component is mounted.
2) Removed the condition to check response results as these checks are already done in the JSX return. Ex-> display no results found if length is 0 and otherwise.
=> fixed mine route issue

__tests__/Unit/Components/TaskList.test.tsx, src/components/tasks/TaskList/TaskList.tsx, src/components/tasks/card/card.module.scss, src/components/tasks/constants.js, src/pages/index.tsx
Closes Phase-1 [367](https://github.com/Real-Dev-Squad/website-status/issues/367)
- Currently, status-site  has  in-progress task  list accordion, on clicking on it shows list of tasks. 
https://user-images.githubusercontent.com/29247011/215776927-9bafb645-d78f-47d4-8223-2474d1e910f7.mp4
- Intially on clicking according we will be showing 3 only tasks and a see more button, and on  each click on **see more** button, we will add 5 more items to the in-progress task list. Once all tasks are rendered **see more button** will be unmounted.
- Further on closing or again opening accordion will show all tasks without **see more** button. 
https://user-images.githubusercontent.com/29247011/215778545-82330018-b7e4-430a-8e83-24429491ed6d.mp4
- Yes  [ x ] 
- No  [  ]
=> See More For Tasks

src/components/tasks/card/index.tsx
Fixes: #480 
Changes:
In edit mode, the ends on date is changed without hitting enter in this PR,
Previously that was not the case, after changing the date, enter was to be hit
=> update end date on selecting the date

.husky/pre-commit, src/components/Accordion/Accordion.stories.tsx
This PR is to improve the developer experience for developers working on the status site.
It ensures a prettier check is run before committing the file to the repository.
in case the prettier check fails developers can run `yarn prettier:fix` to fix the prettier issue.
=> add pre commit hook to fix prettier issues before commit

__tests__/Unit/pages/issues/Issues.test.tsx
THere was a new folder named `Pages`(capital P) I moved the issues to a precreated folder named `pages/issues`(small P)
=> move issues test from a seperate pages folder to common pages folder

src/components/tasks/card/card.module.scss
**Description:**
This pull request addresses the issue of task card titles not being displayed correctly when the title is long and wrapping to multiple lines. The proposed changes aim to improve the task card title display by ensuring that long titles are shown in a single line with an ellipsis (...) to indicate that the title has been truncated.
**Changes Made:**
1. Updated the CSS styles for task card titles to enforce a single line display.
2. Added the text-overflow: ellipsis property to truncate long titles with an ellipsis when they exceed the available width.
**After Changes**
https://github.com/Real-Dev-Squad/website-status/assets/70854507/e51cac31-de91-489a-95e9-28db10d09209
=> Task Card Title Display Enhancement

src/components/tasks/card/ConditionalLinkWrapper.tsx, src/components/tasks/card/card.module.scss
When we add feature flag(?dev=true)  then card long title go outside of the task-card
-  test is not required
https://github.com/Real-Dev-Squad/website-status/assets/107163260/2f568593-a8d5-4afe-acf7-a28b6ab5028c
https://github.com/Real-Dev-Squad/website-status/assets/107163260/83714b51-7cd6-4eb1-b030-46176db8b0cf
https://github.com/Real-Dev-Squad/website-status/assets/107163260/86910258-ff79-4410-b05c-f056e7363a26
=> fixed task card long title (after adding feature-flag)

__mocks__/db/issues.ts, __tests__/Unit/Components/Issues/Card.test.tsx, package.json, src/components/MarkdownRenderer/MarkdownRenderer.tsx, src/components/issues/Card.module.scss, src/components/issues/Card.tsx, src/interfaces/issueItem.type.ts, src/styles/issues.module.scss, yarn.lock
**Description:**
I have added a *markdown-to-jsx* package to convert the markdown content to JSX. This package converts the markdown content to JSX and then renders it on the page. For this, I have created a new component called *MarkdownRenderer* which takes the markdown content as a prop and converts it to JSX using the *markdown-to-jsx* package. And I also added the user and assignee `html_url` to the issue card so that the user can directly go to the user's or assignee's profiles by clicking on the link.
**Screenshot**
**Before:**
**After:**
https://github.com/Real-Dev-Squad/website-status/assets/70854507/04f10b15-9175-47cd-bd7f-be8da0f97b71
=> Add library for render Markdown in HTML

src/components/ProgressForm/ProgressForm.module.scss, src/components/ProgressForm/ProgressHeader.tsx, src/components/ProgressForm/ProgressLayout.tsx
Progress form is not responsive, and looks very odd on small screens
The margins and padding added to the form break it in mobile view. fixed the form to look consistent and appealing to the user even in mobile phones.
=> fix styles of progress form to be responsive on small screens

.env.development, __tests__/Unit/Components/Tabs/Tab.test.tsx, src/components/Tabs/index.tsx, src/components/tasks/TasksContent.tsx, src/constants/constants.ts, src/interfaces/task.type.ts
https://github.com/Real-Dev-Squad/website-status/issues/608
Rearrange the task content tab and also rename some task content
Arrangements should be in this form -
IN_PROGRESS -> ASSIGNED -> AVAILABLE -> NEEDS_REVIEW -> IN_REVIEW ->VERIFIED -> MERGED -> COMPLETED
Tabs that need to be renamed -
AVAILABLE - UNASSIGNED
COMPLETED- DONE
Before change - 
After change - 
https://github.com/Real-Dev-Squad/website-status/assets/82165483/623071db-7e1c-499a-85c4-5f8769817fc0
Due to Errors and in-consistency in files, I have closed this PR 
https://github.com/Real-Dev-Squad/website-status/pull/623
=> Re-Fractor the task content tab

__tests__/Unit/Components/Searchbar/searchbar.test.tsx, __tests__/Unit/pages/Dashboard/dashboardTest.test.tsx, src/components/Dashboard/Dashboard.module.scss, src/components/Dashboard/Searchbar.tsx, src/pages/dashboard/index.tsx
This pull request focuses on enhancing the Dashboard page of the Status Site project. It involves removing unused code, improving the responsiveness of the search bar component, and adding tests to ensure reliable functionality. The changes aim to improve the user experience and maintainability of the Dashboard page.
1. Remove Unused Code:
- Identify and remove any unused code or components from the Dashboard page to optimize the codebase and improve performance.
2. Fix Responsive Search Bar Component:
- Enhance the responsiveness of the search bar component on the Dashboard page to ensure it behaves correctly on different devices and screen sizes.
3. Add enabled and disabled styles to the search button:
- Add styles to make the search button visually enabled and disabled 
4. Add Tests:
- …
=> Improve Dashboard Page of Status Site

src/pages/issues/index.tsx
Fix the code to render IssueList in /issues route.
On every input change on the search field, the issueList was being re-rendered. This was because the IssueList components was controlling the state of the SearchField component as well. 
I fixed this issue by refactoring the code and moving the search field-related text to the SearchField component.
Fixes #605 
Before the changes, the profiler shows it was re-rendered every time I typed something in the text box.
After the change, the profiler shows no re-rendering of the IssueList while changing the search field text
=> refactored code to trigger less re-rendering

__tests__/Unit/Components/Header/Header.test.tsx, next.config.js, src/constants/header-categories.ts, src/pages/tasks/index.tsx
Change make `/tasks` route to get tasks data instead of `/`
closes #672
=> add /tasks route for tasks page

src/components/ProgressForm/ProgressForm.module.scss, src/components/ProgressForm/ProgressLayout.tsx, src/components/standup/standupContainer.module.scss
- #666 
The progress banner and the standup update form are now responsive with a proper layout. 
https://github.com/Real-Dev-Squad/website-status/assets/53934353/e08d5d36-ceb3-4805-a211-8fec0db1bdaa
https://github.com/Real-Dev-Squad/website-status/assets/53934353/c6f05db6-45c3-4b90-8f40-d784fcf7abcb
=> Fix : banner responsiveness for the task progress and standup feature

src/components/tasks/card/index.tsx
Reverts Real-Dev-Squad/website-status#706
replacing assigneeName with event.target.innerHTML is sending empty string which throws an error of 'assignee' cannot be empty.
=> Revert "fixed editing of title field"

src/hooks/useAuthenticated.ts
close #713 
Currently, mine tab can't able to fetch user details to mark it as logged in so to set it as logged in we have to pass isSuccess as dependent in useeffect
=> Fix user loggedin from  mine tab

src/components/tasks/card/index.tsx
quick fix: changed hardcoded vlaue in handleChange to event.target.value.
Our handleChange function is used to edit the details on card component such as title, date, assigneeName. 
Earlier it was hardcoded to assigneeName, so even we change title it takes assigneeName as value.
=> quick fix: changed hardcoded vlaue in handleChange to event.target.value

__tests__/Unit/Components/IdleUsers/Card.test.tsx, src/components/idleUsers/card/index.tsx, src/constants/url.ts
**Issue Reference:** #740 
**Description:**
This pull request addresses issue #740 , where the "Idle Users" card in the status site's idle users dashboard redirects users to the "Members" page, causing confusion for external users since not all idle users are members of the organization. This pull request proposes a solution to redirect the "Idle Users" card to the "User Management" page instead, offering a more comprehensive view of all idle users, including both members and non-members.
**Proposed Changes:**
1. Modify the "Idle Users" card click behavior to redirect to the "User Management" page.
2. Update the necessary links and routes to ensure seamless redirection.
**Reasoning:**
Redirecting to the "User Management" page improves the user experience for external users by providing a …
=> fix idle users card to redirect to user management page

__tests__/Unit/Components/Select/Select.test.tsx, __tests__/Unit/Components/Tasks/TasksContent.test.tsx, src/components/Select/index.tsx, src/components/Select/select.module.scss, src/components/Tabs/index.tsx, src/components/tasks/TasksContent.tsx, src/styles/tasks.module.scss, src/types/Select.d.ts, src/utils/getChangedStatusName.ts
https://github.com/Real-Dev-Squad/website-status/issues/760
Currently the task status tabs look cluttered in mobile.Added dropdown for task status in mobile so it looks cleaner.
Created Select component for the same and added tests as well
- Yes
Test coverage:
-------------------------------
=> 760 add dropdown for task status mobile

__tests__/Unit/utils/getActiveTab.test.ts, src/components/tasks/TasksContent.tsx, src/utils/getActiveTab.ts
**Description:**
This Pull Request addresses issue #776 which proposes replacing underscores (_) with hyphens (-) in URL parameters to improve the readability and adhere to modern web conventions.
1. Updated the application's routing and URL parameter handling to recognize hyphens (-) as separators instead of underscores (_).
2. Added support for both formats: URLs with underscores and hyphens to ensure backward compatibility.
3. Refactored relevant code to handle URL parameters consistently with hyphens.
Performed extensive testing to ensure the following scenarios:
1. URLs with underscores are correctly processed and function as expected.
2. URLs with hyphens are now interpreted correctly, and the application behaves as intended.
3. Existing URLs with underscores continue to work …
=> Fix URL Parameter Format: Replace Underscores with Hyphens

__tests__/Unit/Components/Tasks/TasksContent.test.tsx, __tests__/Unit/hooks/useIntersection.ts.test.tsx, src/components/tasks/TasksContent.tsx, src/hooks/useIntersection.ts
As part of this implementation, we will use the Intersection Observer API to automatically fetch the next task when the user reaches the end of the task list container. This will eliminate the need for the "Load More" button, providing a smoother user experience.
https://github.com/Real-Dev-Squad/website-status/assets/70854507/fc0ae344-ad0b-4e61-bd4c-21033bcd474e
=> FEATURE: Add intersection observer for fetching task

__tests__/Unit/hooks/tasksApi.test.tsx, src/app/services/tasksApi.ts, src/components/tasks/TaskList/TaskList.tsx, src/components/tasks/card/index.tsx, src/interfaces/task.type.ts
https://github.com/Real-Dev-Squad/website-backend/issues/1224
This pull request (PR) aims to removes the userStatus flag, which is currently in use to track user status based on task. The feature is now stable and has been in prod since more than 3 weeks and as confirmed with Ankush we can remove this feature flag.
No
None
=> Remove users status feature flag

src/components/tasks/card/index.tsx, src/interfaces/issueItem.type.ts, src/interfaces/task.type.ts
fix task types to accommodate ends on field to number in task type as backend returns it as a number.
also add an optional task id field to issues in to accommodate new changes in the backend to return task id of github issue if task is created.
=> refactor endsOn type and acccomodate task id in issue

src/components/Layout/Layout.module.scss, src/components/Select/select.module.scss
The card have min width of 267px because of the content inside it, like progress bar. Also the select have with 20em changed it to 100%. Now the navbar is not detaching for screen size of iPhone 4 or less. 
https://github.com/Real-Dev-Squad/website-status/assets/55151241/2684caff-98b2-4d8f-ab0e-7dc13609661d
=> added responsiveness to the in-review page

__tests__/Unit/Components/Issues/Card.test.tsx, src/components/issues/Card.tsx
**Issue:** #810 
**Changes Made:**
- Updated access control settings for the "Convert to Task" functionality on the issues page.
- Modified the code logic to restrict access to the "Convert to Task" option for non-admin/super users.
**Testing Done:**
- Tested the changes using different user roles (admin, superuser, regular user) on the issues page.
- Verified that only administrators and super users can see and use the "Convert to Task" option.
- Confirmed that regular users no longer have access to the "Convert to Task" option.
**Related Issues:**
Closes #810
=> disable convert to task button for non admins/superusers

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/index.tsx
- https://github.com/Real-Dev-Squad/website-status/issues/814
Currently, if the superuser presses the save button without changing anything then there is an unnecessary patch call that is happening
https://github.com/Real-Dev-Squad/website-status/assets/111434418/401bc114-b960-42d7-9a7a-8938e04630e0
=> fix unnecessary api call for updating task details

__mocks__/db/issues.ts, __tests__/Unit/Components/Issues/Card.test.tsx, src/components/issues/ActionForm.tsx, src/components/issues/Card.module.scss, src/components/issues/Card.tsx
This pull request addresses the requirement to integrate a form directly within the issues page for assigning issue tickets. The form will only be accessible when the "dev = true" flag is enabled.
- Implemented a form component to assign issue tickets directly from the issues page.
- Added a conditional check to ensure the form is displayed only when the "dev = true" flag is enabled.
Integrating the assignment form within the issues page streamlines the process of assigning tickets, reducing the need to navigate to a separate assignment page. The "dev = true" flag ensures that this feature is only available to developers during the development and testing phases.
- Tested the form integration and conditional display with the "dev = true" flag both enabled and disabled.
- Verified that the …
=> Integrate Issue Assignment Form on Issues Page

__tests__/Unit/Components/ProgressForm/ProgressHeader.test.tsx, __tests__/Unit/Components/Standup/StandupContainer.test.tsx, __tests__/Utils/getCurrentDate.test.ts, src/components/ProgressForm/ProgressHeader.tsx, src/components/standup/index.tsx, src/components/standup/standupContainer.module.scss, src/constants/constants.ts, src/utils/getCurrentDate.ts
**Issue Ticket**
- Closes #846 
**Parent Issue -**
- #837 
Overview
As the Standup feature is deployed on Production under the feature flag, remove the feature from the feature flag I asked developers in the team for review and I got a few suggestions from developers. so this project will be an updated version of the existing feature in production.
Context
As per the suggestions received, this project is important from a user perspective because this project will make the user experience much better and also will remove the confusion between the users while filling up the standup form.
Issues to Be Addressed - 
#847
=> [FEATURE] - Standup Feature Update(Milestone-1) 

__mocks__/handlers/task-details.handler.ts, __tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/Details.tsx, src/components/taskDetails/task-details.module.scss
Main issue: #774 
This is a follow-up PR of #827 to resolve review comments.
Review comments:
1) Use Link instead of button
2) Write proper CSS.
Changes : 
1) A link is used instead of a button for displaying the git issue link on the task details page.
2) Modified the tests accordingly for the link.
3) Removed unused CSS.
A review comment in earlier PR was to use single line. But this formatting is done by Prettier so I could not add it in a single line.
[src/components/taskDetails/index.tsx](https://github.com/Real-Dev-Squad/website-status/pull/827/files/0c3718f538f764b7785fd4a296ab20a23848371a#diff-543be524388e0f526cb5ff91b3af518cf41ed9175d95a349a074418e508cc298)
- [ ✓] Yes
Before :
After:
[gitIssue2.webm](https://github.com/Real-Dev-Squad/website-status/assets/41846637/e696e4b6-5f59-40 …
=> Fix: Display Link instead of button for git issue link in task details page.

__mocks__/db/tasks.ts, __tests__/Unit/Components/Tabs/Tab.test.tsx, __tests__/Unit/Components/Tasks/FilterModal.test.tsx, __tests__/Unit/Components/Tasks/TaskSearch.test.tsx, __tests__/Unit/Components/Tasks/TasksContent.test.tsx, __tests__/Unit/utils/getActiveTab.test.ts, src/components/Select/index.tsx, src/components/Tabs/index.tsx, src/components/tasks/TabSection.tsx, src/components/tasks/TaskSearch/FilterModal.tsx, src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TasksContent.tsx, src/constants/constants.ts, src/interfaces/task.type.ts, src/pages/tasks/index.tsx, src/types/Select.d.ts, src/utils/getActiveTab.ts, src/utils/getChangedStatusName.ts
As `AVAILABLE` and `COMPLETED` task status are being depreciated and `UNASSIGNED` and `DONE` are to be added to status site. When `UNASSIGNED` or `DONE` is clicked we'll retrieve tasks with status `UNASSIGNED` or `DONE` respectively.
This is under feature flag.
- Changes are made to retrieve tasks with status `UNASSIGNED` when `UNASSIGNED` is clicked.
- Changes are made to retrieve tasks with status `DONE` when `DONE` is clicked.
https://github.com/Real-Dev-Squad/website-status/assets/77037622/b2ef5a0b-678d-455e-a70b-e04f4a951245
https://github.com/Real-Dev-Squad/website-status/assets/77037622/a83da599-90fa-42d3-be06-1974e0323b12
=> Changing task status to DONE and UNASSIGNED

__tests__/Unit/Components/TaskList/TaskList.test.tsx, src/components/tasks/TaskList/TaskList.tsx, src/components/tasks/constants.ts
In this PR, I removed the old see more button functionality from the TaskList components. This was done because the new Load More button functionality is now in place.
Also, fix the typo in the PR template.
=> REFACTOR: removed old see more button from TaskList components

src/components/tasks/card/card.module.scss
Closes #877 
Progress Indicator Overflow
Progress indicator color overflows content area of the indicator. Changing colored area's height relative to it's parent solves this issue.
before:
after:
=> Fix: Progress Indicator Color Overflow

src/components/head/index.tsx
closes #893 
Fix Dymnaic Title Hydration Problem
This PR fixes the dynamic title hydration problem where the title was being rendered differently on the server and client. On each page reload, title change after initial loading is fixed. Also no warning in dev console regarding this issue.
This fix is achieved by using string interpolation for dynamic title, which creates only one text node inside title element.
Title is properly rendered.
https://github.com/Real-Dev-Squad/website-status/assets/87164140/77d85473-4376-45c6-92be-c9b0891aa6a8
Related warning not present in dev console
=> Fix: Dynamic Title Hydration Problem

__tests__/Utils/taskQueryParams.test.ts, src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TasksContent.tsx, src/constants/tasks.ts, src/utils/taskQueryParams.ts
**Closes the following Issues**
- #896
- #917 
Multiple Assignee Tasks Search
TasksContent Component Refactor
Need to integrate multiple assignee tasks search support in frontend.
TasksContent component has become too large and contains unnecessary useState (s), resulting in hard to maintain and unnecessary re-renders. While integrating multiple assignee search support, unnecessary re-renders were causing bugs and test fail. So, have refactored the component in same PR.
- TasksComponent Refactored
- Multiple assignee tasks search integrated
- Disabled spellCheck on tasks search box input.
This PR addresses two issues.
https://github.com/Real-Dev-Squad/website-status/assets/87164140/7753e637-5992-4213-ae93-833c56d5ce25
Video demonstrates multiple assignee tasks search and fixed …
=> Multiple Assignee Tasks Search and TasksContent Component Refactor

__tests__/Unit/Components/ProgressForm/ProgressForm.test.tsx, src/components/ProgressForm/ProgressForm.tsx
When going to the update progress we get redirected to form to update our task progress. In initial state there's no data present in the from and the button is disabled in state(as it looks in UI). But when we try to click the button with empty form it gets clicked and the API is also being called which shouldn't happen. https://github.com/Real-Dev-Squad/website-status/issues/916
https://github.com/Real-Dev-Squad/website-status/assets/40158457/c030f461-10e0-4baa-84b8-bc1dbf114e7b
=> updated submit button logic for progress form

src/components/tasks/card/card.module.scss, src/components/tasks/card/index.tsx
- On [Tasks Page](https://status.realdevsquad.com/tasks?q=status%3Aall), when the title text doesn't fit in one line, the card title has white-space set to no-wrap causing the UI to break.
- PFB the screenshots
- With white-space set to normal prevents UI break as below:
- CSS Fixes: When the title text doesn't fit, it gets truncated and instead of setting no-wrap to white-space we let the text wrap preserving spaces by setting white-space to pre-wrap
- [✅] Yes
- ![test ss](https://github.com/Real-Dev-Squad/website-status/assets/75213145/220eb3e0-b4a9-408c-97a4-cd955fefdebc)
https://github.com/Real-Dev-Squad/website-status/assets/75213145/674aa82c-4495-4c3f-8b66-ffe45d02a644
NA
=> [Bug] Status Site - Task cards are breaking UI due to title text getting truncated without text wrap

src/helperFunctions/getIdleSinceText.ts
- The idle page where we show idle users and their time/day for how long they have been idle. So to show time/day we are not using UTC time format.
- So i have added UTC time format there.
- Didn't write any test cause it is not require and test are already written for card component.
Image proof :-
=> add UTC time format on idle page

src/components/tasks/card/card.module.scss
Followup on issue #928 
1. Width of the task cards isn't consistent across all tabs
2. Incase of title with a longer word, word doesn't break and  wrap to next line in smaller mobile screens. Hence css fixes has been made in this PR
Before:
- ![For inconsistent width](https://github.com/Real-Dev-Squad/website-status/assets/75213145/24c16fcd-2596-4ea2-888c-4492d5340a42)
- ![For inconsistent width](https://github.com/Real-Dev-Squad/website-status/assets/75213145/9c92a4bb-6564-4d2c-b5d2-61b83295747e)
After:
- For inconsistent width fix refer this [video here](https://github.com/Real-Dev-Squad/website-status/assets/75213145/2659ec3c-a78e-43c9-a583-20ef690db888)
Before:
- ![For issue 2](https://github.com/Real-Dev-Squad/website-status/assets/75213145/eb71c14a-5010-4a11-a561-4cb0a734d228) …
=> Issue 928 Followup: - Width of task cards isn't consistent  across different task-status tabs

__tests__/Unit/Components/Header/Header.test.tsx, src/components/Header/index.tsx, src/components/PullRequestList/index.tsx, src/constants/header-categories.ts, src/pages/pull-requests/index.tsx
closes #924 
**Fix Routes Naming**
The naming of these routes doesn't follow conventions and should be updated following routes naming convention.
Open PRs: `https://status.realdevsquad.com/openPRs`
Stale PRs: `https://status.realdevsquad.com/stale-pr`
The updated routes are now,
Open PRs: `https://status.realdevsquad.com/pull-requests?state=open`
Stale PRs: `https://status.realdevsquad.com/pull-requests?state=stale`
There was an issue in `PullRequestList` component (used in these routes) related to duplicate key, fixed this problem with unique key values.
The updated routes are available in Header links under dev=true feature flag.
**Before**
**After**
https://github.com/Real-Dev-Squad/website-status/assets/87164140/a584177d-9841-4d48-bcd3-02526b95c8f6
The updated routes are under …
=> Fix Routes Naming

__tests__/Unit/Components/Issues/ActionForm.test.tsx, __tests__/Utils/time.test.ts, src/components/issues/ActionForm.tsx, src/utils/time.ts
- #902
When creating a task from an issue and assigning it to someone, it's important to establish a reasonable timeframe for task completion. To streamline this process and ensure clarity, we added a default "Ends On" date for task assignments i.e 2 days from the current day.
No
today date is 20/10/2023
None
=> set the default ends on field with 2 days offset

src/components/issues/Card.tsx, src/components/issues/TaskRequestForm.tsx, src/utils/time.ts
Developer Name: @Ajeyakrishna-k 
- #911 
- Previously end date had today's date as default value. This PR sets the default value of end date seven days from today.
- Removes description field if falsy.
Backend changes
Frontend Changes
Is Under Feature Flag 
Database changes
Test coverage:
Screenshot:
=> Fixes wrong initial value of ends on date in task request form

__tests__/Unit/Components/Tasks/Card.test.tsx, src/components/tasks/card/index.tsx
Issue Ticket Number:- https://github.com/Real-Dev-Squad/website-status/issues/936 , https://github.com/Real-Dev-Squad/website-status/issues/967
Show the task status on task card.
No
No
Yes
No
No
No
Deployment notes
No
No
Yes
Prev
New
=> Remove feature flag from showing the status in task card and handle edit view.

__tests__/Unit/pages/issues/Issues.test.tsx, src/components/issues/ActionForm.tsx, src/pages/issues/index.tsx
Closes #891 
- #891 
On Issues page api call for issues and assignee are being done before any input is provided. During assignee suggestion for task assignment api calls are being made even when assignee input is empty.
This is a fix change that affects both features under feature flag and out of feature flag.
Before:
After:
https://github.com/Real-Dev-Squad/website-status/assets/87164140/2e2ba175-e54d-423f-a189-f0eb12113973
=> Fix APIs Being Called Before Input Is Provided

__tests__/Unit/Components/Tasks/TaskStatusEditMode.test.tsx, src/components/tasks/card/TaskStatusEditMode.tsx, src/components/tasks/card/index.tsx
**Design Doc** https://docs.google.com/document/d/1C3oizE01vH6cQHRtoJbA7-QHDoDhHuPiMllqvh6v5cM/edit?usp=sharing
- When super_user wants to change the status of a task card from "status-site," then they get only one option i.e. “DONE” under the feature flag.
https://github.com/Real-Dev-Squad/website-status/assets/107163260/4d0ec009-7906-47e1-a8b2-82c2907be09b
=> super_user only change status done under feature flag

__tests__/Unit/Components/Tasks/TaskStatusEditMode.test.tsx, src/components/tasks/card/TaskStatusEditMode.tsx
-  Remove "COMPLETED" task status from task card under edit mode
- Remove feature flag i.e. now super users to see "DONE" task status only and not "COMPLETED" task status in task card under edit mode
- Under feature flag changes pr which merged before: https://github.com/Real-Dev-Squad/website-status/pull/991
Is Under Feature Flag 
Database changes
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
Is Development Tested?
**Before Changes**
https://github.com/Real-Dev-Squad/website-status/assets/107163260/4329ded2-4aff-47a7-98fe-533c432e09b8
**After Change video:**
https://github.com/Real-Dev-Squad/website-status/assets/107163260/2e074569-6548-408e-aa1f-9902cd570857
**Test stats:**
=> Remove Feature Flag - Super User Sees "DONE" Task Status and Excludes "COMPLETED" Task Status in Task Card Edit Mode

__tests__/Unit/Components/Tasks/TaskStatusEditMode.test.tsx, src/components/tasks/card/TaskStatusEditMode.tsx
Reverts Real-Dev-Squad/website-status#1013
Reason: removing feature flag without running 1 time script break things on prod
=> Revert "Remove Feature Flag - Super User Sees "DONE" Task Status and Excludes "COMPLETED" Task Status in Task Card Edit Mode"

__tests__/Unit/Components/Tasks/TaskSearch.test.tsx, src/components/tasks/TasksContent.tsx
1. Task search should not show `status:all` in dev mode, as it won't make sense once we have suggestions.
NA
https://github.com/Real-Dev-Squad/website-status/assets/56365512/945beb60-7097-4820-a98b-87054437ab4a
=> Removed default status from Task Search

__tests__/Unit/Components/Header/Header.test.tsx, src/components/Header/index.tsx, src/constants/header-categories.ts, src/pages/openPRs/index.tsx, src/pages/stale-pr/index.tsx
Closes #1029  
- #1029 
Older pull requests routes(open prs and closed prs) with unconventional naming are replaced with updated routes which were under feature flag.
This PR takes a feature(#935 ) out of feature flag.
Before:
https://github.com/Real-Dev-Squad/website-status/assets/87164140/1654811f-5084-41e7-ab7c-659b9d16ebff
After:
https://github.com/Real-Dev-Squad/website-status/assets/87164140/5968eda3-1bef-4703-a0c7-61cc7394053d
=> Replace PR Routes with Updated Routes and Remove Feature Flag

__tests__/Unit/Components/Tasks/Option.test.tsx, __tests__/Unit/Components/Tasks/Options.test.tsx, src/components/tasks/TaskSearch/Suggestion/Option.tsx, src/components/tasks/TaskSearch/Suggestion/Options.tsx, src/components/tasks/TaskSearch/Suggestion/option.module.scss
Added functionality to display suggestions, if found, otherwise show `no suggestion found`
- https://github.com/Real-Dev-Squad/website-status/pull/1036
- https://github.com/Real-Dev-Squad/website-status/pull/1037
1. Should render suggestion if typed input has more than 2 characters and has no key
2.  Should render suggestion if typed input has more than 2 characters in value if key is present
3. Should show `no suggestion found` if no suggestion is found
NA
https://github.com/Real-Dev-Squad/website-status/assets/56365512/61968123-9701-4f8b-9bc7-f50b10e56d3e
https://github.com/Real-Dev-Squad/website-status/assets/56365512/9f5c5e20-5e9f-4b91-b9e2-3d6de34dc0d0
<hr/>
=> Feat : Added options for task search

src/components/navBar/navBar.module.scss
On opening nav dropdown in mobile mode the top right corner profile or github moved a little.
-  Yes
=> Fixed displacement of profile dropdown in mobile mode

__tests__/Unit/Components/Tasks/TaskSearch.test.tsx, src/components/tasks/TaskSearch/Suggestion/Options.tsx, src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TaskSearch/tasksearch.module.scss
1. Enabled complete functionality of new task search
2. Fixed filter modal positioning issue
3. Enabled test cases for task search
https://github.com/Real-Dev-Squad/website-status/assets/56365512/62e42bc8-ba59-46e6-8fcf-28e6860f6919
=> Made new task search functional

__tests__/Unit/hooks/taskRequestApi.test.tsx, package.json, src/app/services/taskRequestApi.ts, src/components/issues/Card.tsx
-  Real-Dev-Squad/website-status#1050
In this pull request, I have addressed the issue described in Real-Dev-Squad/website-status#1050. The problem was related to the absence of GitHub issue ticket links for tasks created via task requests. 
Is Under Feature Flag 
Database changes
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
Is Development Tested?
Tested in staging?
| File                              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
|-----------------------------------|---------|----------|---------|---------|-------------------|
|  taskRequestApi.ts                     |     100 |      100 |     100 |     100 |                   
|  Card.tsx                              |   38.35 |    47.05 |    37.5 | …
=> fix: added github issue link to task request post call

src/components/taskDetails/progress-details.module.scss, src/components/tasks/card/card.module.scss, src/styles/issues.module.scss
Date: 23rd Jan 2023
Developer Name: @ajoykumardas12 
---
closes #1084 
There was a issue with loading background because of using SCSS lighten() method which made the background non-transparent. I missed this issue earlier thinking loading feels different because of server being slow.
Changes:
- Using rgba() instead of lighten() for loading background and modal background.
- Have made issues page submit button background slightly different background than input box.
Before: 
https://github.com/Real-Dev-Squad/website-status/assets/87164140/5bf57d74-54b2-4110-8392-ce84aea78b68
After
https://github.com/Real-Dev-Squad/website-status/assets/87164140/cadf3e21-aaa1-4327-a727-9ebe6616ecf5
=> Fix Loading Background

__tests__/Unit/Components/Calendar/UserSearchField.test.tsx, package.json, yarn.lock
Date:  31 Jan 2024
Developer Name: @VinayakaHegade
---
closes #1092 
This PR adds tests for SearchField component created as part of calendar feature in status site.
@testing-library/user-event package has been added to test interactions. Was facing issues similar to issues mentioned in the below links with fireEvent, so used userEvent.
[fireEvent.change not always firing on sequential calls](https://github.com/testing-library/react-testing-library/issues/591)
[Onchange event not being fired when using fireEvent.change](https://github.com/testing-library/react-testing-library/issues/532)
[Why it is recommended to use user-event to test interactions instead of fireEvent](https://testing-library.com/docs/user-event/intro/#:~:text=The%20problem%20is,with%20your%20components.)
=> Add tests for SearchField component

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/app/services/taskDetailsApi.ts, src/components/taskDetails/Details.tsx, src/components/taskDetails/index.tsx, src/constants/url.ts, src/interfaces/task.type.ts, src/interfaces/taskDetails.type.ts
Date: 29/01/2024
Developer Name: Palak Gupta (palakgupta2712)
---
resolves #1088 
Conditionally show the icon that will redirect user to extension-requests/taskId={taskId}, only if there is any pending extension request for that particular task.
As per current documentation format, so changes were made.
<details>
<summary>Scenario 1</summary>
- isPendingExtensionRequest is `false` for that task, 
</details>
<details>
<summary>Scenario 2</summary>
- isPendingExtensionRequest is `true` for that task,
- On clicking the icon it will redirect to `/extension-requests?order=asc&q=taskId%{taskId}`
<details>
<summary>test covergae</summary>
</details>
=> feat/issue-1088:  show icon for pending extension request for a task

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/app/services/taskDetailsApi.ts, src/components/taskDetails/Details.tsx, src/components/taskDetails/index.tsx, src/constants/url.ts, src/interfaces/taskDetails.type.ts
…(#1095)
* feat/issue-1088:  show icon for pending extension request for a task in tasks details page
Date: 2/02/2034
Developer Name: Palak Gupta
---
https://github.com/Real-Dev-Squad/website-status/pull/1095
#1088 
Conditionally show the icon that will redirect user to extension-requests/taskId={taskId}, only if there is any pending extension request for that particular task.
Tested in staging
Staging proof for #1088 
https://github.com/Real-Dev-Squad/website-status/assets/61227144/6369dc78-dba4-45f4-b902-7a44d0fb13c2
=> feat/issue-1088:  dev to main sync

__tests__/Unit/Components/Issues/TaskRequestForm.test.tsx
Date: 07-02-2024
Developer Name: @VinayakaHegade 
---
closes #1101 
Fixed the test "renders form with default values" for the TaskRequestForm component which was failing when run in a time period that does not overlap with UTC. For more details please refer #1101
=> Fix "renders form with default values" test for  TaskRequestForm component

__tests__/Unit/Components/Tasks/ProgressUpdateCard/ProgressUpdateCardPresentation.test.tsx, __tests__/Unit/Components/Tooltip/Tooltip.test.tsx, src/components/common/Tooltip/Tooltip.tsx, src/components/taskDetails/ProgressUpdateCard/LatestProgressUpdateCard.tsx, src/components/taskDetails/ProgressUpdateCard/LatestProgressUpdateCardPresentation.tsx, src/components/taskDetails/ProgressUpdateCard/ProgressUpdateCard.tsx, src/components/taskDetails/ProgressUpdateCard/ProgressUpdateCardPresentation.tsx, src/components/taskDetails/ProgressUpdateCard/latest-progress-update-card.module.scss, src/components/taskDetails/ProgressUpdateCard/progressUpdateCard.types.ts
Date: 17 feb 2024
Developer Name: @skv93-coder 
---
https://ant.design/components/tooltip
Makes tooltip component more reuseable
[screen-capture (7).webm](https://github.com/Real-Dev-Squad/website-status/assets/68867418/2ec1cea1-86da-4c48-bd52-544d002ee9c1)
<details>
</details>
<details>
</details>
=> Made tooltip component reusable

src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TaskSearch/tasksearch.module.scss
Date: 17-02-2024
Developer Name: @VinayakaHegade 
---
https://github.com/Real-Dev-Squad/todo-action-items/issues/218#issuecomment-1947313328
- It fixes chevron overflow when filter options modal opens.
- And filter options modal position for small screens.
before
https://github.com/Real-Dev-Squad/website-status/assets/88454618/999b066d-f137-4e96-899b-aefa11fc42b4
after
https://github.com/Real-Dev-Squad/website-status/assets/88454618/83fe5ccf-6481-429b-83eb-34dbd2de9d8d
gap added between modal and search box
=> style: fix chevron overflow and fiter options modal position in small screens.

__tests__/Unit/pages/calendar/calendar.test.tsx, jest.config.js, src/pages/calendar/index.tsx
Date: 28-02-2024
Developer Name: @VinayakaHegade 
---
#1103 
This PR adds tests for the calendar page. Currently, we are only able to test predictable statuses, such as "displays holiday message on clicking a Sunday". Other statuses like "active", "idle", and "ooo" cannot be tested with the current implementation. Once the calendar page code is refactored, tests for these remaining statuses will be added.
And change in jest config file is to fix the below issue i was facing.
<details>
</details>
=> Add tests to calendar page for steady status data.

src/components/taskDetails/index.tsx
* bug/extension-req-url: fix extension request url in task details page
---------
Date: 30th March 2024
Developer Name: Palak Gupta
---
closes #1168
Expected Behavior
On clicking the extension-request show the whole list of the extension-request for that particular task
The list of extension-requests are not in descending order, due to which older Extension Request shows up first.
Current Behavior
On clicking the extension-request icon, show the whole list of the extension-request for that particular task, with status = "PENDING" and sort the data in descending order of creation of the extension request.
https://github.com/Real-Dev-Squad/website-status/assets/61227144/967bcea6-ef34-4d75-92dc-89c7a258b4e4
<details>
</details>
=> dev to main sync

__tests__/Unit/Components/Calendar/UserSearchField.test.tsx, src/components/tasks/card/index.tsx
Date: 30 April, 2024
Developer Name: Tejas
---
#1138
The progress bar of the task is only related to the in-progress status. So it should be visible only if the status of the task is in progress.
So, this PR updates the progress bar, only showing it when the task is in "IN_PROGRESS
- [] Yes
</details>
=> The progress bar should be visible only when the task is in progress

src/components/tasks/TaskSearchDev/TaskSearchDev.tsx
Fix crash on editing field, before suggestions could appear.
Exact steps:
- Enter `status:in-progress` field 
- Do some small change in the field `in-progress`
- Press enter before suggestion could pop up
<details>
<summary>Before Fix</summary>
[Screencast from 27-05-24 06:15:27 PM IST.webm](https://github.com/Real-Dev-Squad/website-status/assets/63191499/fca6f554-70cb-4c7c-a008-d33b20c67a82)
</details>
<details>
<summary>After Fix</summary>
https://github.com/Real-Dev-Squad/website-status/assets/63191499/1609de23-9664-458d-b726-94111d28e763
</details>
<details>
</details>
=> Fix suggestion selection crash bug

__tests__/Unit/Components/Tasks/TaskDropDown.test.tsx, __tests__/Unit/Components/Tasks/TaskStatusEditMode.test.tsx, src/components/taskDetails/index.tsx, src/components/tasks/TaskDropDown.tsx, src/components/tasks/card/TaskStatusEditMode.tsx, src/components/tasks/card/index.tsx, src/constants/constants.ts
Date: June 2 2024
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/website-my/issues/599
This PR removes the Completed label from the status site under the feature flag
BEFORE
AFTER
<details>
</details>
<details>
</details>
=> Removed the completed status

__tests__/Unit/Components/Standup/FormComponent.test.tsx, __tests__/Unit/Components/Standup/MainForm.test.tsx, __tests__/Unit/Components/Standup/StandupContainer.test.tsx, src/components/standup/FormInputComponent.tsx, src/components/standup/MainForm.tsx, src/components/standup/index.tsx
Date: 9 Aug 24
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/website-status/issues/1218
Disabled the button for submission of standup until standup is submitted and remove spaces while submitting.
<details>
[screen-capture (3).webm](https://github.com/user-attachments/assets/2de7c958-a442-4881-abc4-db3e606c3a92)
</details>
<details>
</details>
=> Corrected loading issue and extra space in standup submit

src/components/Modal/modal.module.scss
Date: 10/09/24
Developer Name: Sameer Supe
---
- Closes #1255 
Fixes alert box which pops behind modal overlay. Conflict comes in from similar z-index value(9999) of modal overlay and react-toastify component.
<details>
https://github.com/user-attachments/assets/bcbbf853-bf1d-4b74-8b7e-6d69ae525b07
</details>
<details>
</details>
=> fix alert message on issues page

__tests__/Unit/pages/Mine/Mine.test.tsx, __tests__/Unit/utils/getFilteredTasks.test.ts, __tests__/Unit/utils/getInputValueFromTaskField.test.ts, fixture/task.ts, src/components/Loaders/cardShimmer/index.tsx, src/pages/mine/index.tsx, src/utils/getFilteredTasks.ts, src/utils/getInputValueFromTaskField.ts
Date:  19 Sep 2024
Developer Name: Pankaj Sha
---
- Closes #1262 
This pr adds a filter dropdown component, changes the style of task card and implements filter logic. 
<details>
<summary>Working video</summary>
https://github.com/user-attachments/assets/56dadf8b-a767-4b83-aa7a-f90ff74e2f83
</details>
<details>
</details>
<details>
<summary>Screenshot 2</summary>
</details>
=> Add filter dropdown and change task card style in mine page

__mocks__/handlers/task-details.handler.ts, __tests__/Unit/Components/Tasks/TaskDates.test.tsx, __tests__/Unit/Components/Tasks/TaskDetails.test.tsx, __tests__/Unit/Components/Tasks/TaskHeader.test.tsx, __tests__/Utils/isValidDate.test.ts, src/components/taskDetails/Details.tsx, src/components/taskDetails/TaskDates.tsx, src/components/taskDetails/TaskHeader.tsx, src/components/taskDetails/index.tsx, src/components/taskDetails/task-details.module.scss, src/interfaces/taskDetails.type.ts, src/utils/isValidDate.ts
Date: 15-09-2024
Developer Name: Ayush Sanj
---
- Closes #1252 
1. Date picker alignment issue fixed.
2. Loader like `Saving...` updated after saving the task.
3. Moved States to relevant components.
4. Code refactor.
5. Update relevant test cases.
<details>
https://github.com/user-attachments/assets/f619ae91-2cc1-4367-9a22-adfa237335d6
with extension icon:
https://github.com/user-attachments/assets/849b6bd9-8b07-460b-90fb-5ab07a27ba90
with feature dev flag toggle:
https://github.com/user-attachments/assets/9b54fb07-e22b-4110-9b89-351a6411bf36
</details>
<details>
</details>
Found some states in parent component unnecessarily prop drilled which could have been used in details component. so refactored it. To show the input …
=> Fixes date picker alignment and date value not showing up while editing on task details page

__tests__/Unit/Components/Navbar/Navbar.test.tsx, src/components/navBar/index.tsx, src/components/navBar/navBar.module.scss, src/hooks/useUserData.ts
Date: 8 Oct, 2024
Developer Name: Anuj Chhikara
---
#1268
<details>
<summary>Problem Screenshot</summary>
</details>
<details>
<summary>Solved Screenshot</summary>
</details>
<details>
<summary>Test Coverage</summary>
Earlier coverage
Now coverage
Test Results: All tests passed successfully (7/7) for the Navbar component.
</details>
- **Problem**: When navigating the navbar, the user status briefly displays "Login with GitHub" before showing the user data, leading to a confusing experience for users.
- **Fix**: Implemented a loading skeleton to provide a visual indication while the user data is being fetched, ensuring a smoother transition and a clearer user experience.
- **Impact**: This enhancement reduces confusion and improves the overall user experience by clearly indicating that the …
=> add loading skeleton for user profile in the navbar

__tests__/Unit/pages/Mine/Mine.test.tsx, src/pages/mine/index.tsx
Date: 20 Nov, 2024 
Developer Name: @pankajjs 
---
- Closes #1276
- #1277 
<details>
</details>
=> Dev to Main Sync 

__tests__/Unit/Components/Tasks/Card.test.tsx, __tests__/Unit/pages/Mine/Mine.test.tsx, src/components/Loaders/taskCardShimmer/index.tsx, src/components/Loaders/taskCardShimmer/taskCardShimmer.module.scss, src/pages/mine/index.tsx
Date: 20 Nov, 2024
Developer Name: @pankajjs 
---
- Closes #1283 
This PR fixes the shimmer card component in mine page.
<details>
https://github.com/user-attachments/assets/4953fd97-e9a4-470d-aeab-e8f148738538
</details>
<details>
</details>
Design Doc - https://docs.google.com/document/d/1Y-V7ClFjge1c01ErrFpGgmfZJ6wXZCJ7q2SuLDrcEcY/edit?tab=t.0#heading=h.iwhskjpqyzwf
=> Fix shimmer card component in mine page

__tests__/Unit/Components/ProgressForm/inputWithQuestions.test.tsx, __tests__/Unit/Components/Tasks/ProgressBar.test.tsx, __tests__/Unit/Components/Tasks/ProgressIndicator.test.tsx, __tests__/Unit/Components/Tasks/ProgressSlider.test.tsx, __tests__/Unit/Components/Tasks/ProgressText.test.tsx, __tests__/Unit/Components/Tasks/TaskDetails.test.tsx, __tests__/Unit/Components/Tasks/TaskUpdateModal.test.tsx, __tests__/Unit/pages/Progress/ProgressUpdatesPage.test.tsx, src/components/ProgressForm/InputWithQuestions.tsx, src/components/ProgressForm/ProgressForm.module.scss, src/components/ProgressForm/ProgressForm.tsx, src/components/taskDetails/TaskDetailsSection.tsx, src/components/taskDetails/TaskUpdateModal.tsx, src/components/taskDetails/index.tsx, src/components/taskDetails/task-details.module.scss, src/components/tasks/card/card.module.scss, src/components/tasks/card/progressContainer/ProgressBar.tsx, src/components/tasks/card/progressContainer/ProgressIndicator.tsx, src/components/tasks/card/progressContainer/ProgressSlider.tsx, src/components/tasks/card/progressContainer/ProgressText.tsx, src/components/tasks/card/progressContainer/index.tsx, src/interfaces/task.type.ts
Date: `30th November, 2024`
---
- Closes #1274 
Added modal for updating task progress and percentage
- Restrict progress updates to tasks with status In Progress only.
- Addressed the issue where users could update progress without providing updates or changing task status.
- Ensures better task tracking and accountability.
<details>
https://github.com/user-attachments/assets/83211a7f-cb55-45dd-b15b-8ee1ca4e35f0
</details>
<details>
</details>
- **This PR follows a stack PR approach, so first the test [PR](https://github.com/Real-Dev-Squad/website-status/pull/1291) will be merged into this feature branch, then we can merge this to develop.**
=> feat: added modal for updating task progress and task percentage.

__tests__/Unit/Components/Calendar/UserSearchField.test.tsx, __tests__/Unit/Components/Tasks/TaskDetails.test.tsx, __tests__/Unit/pages/Mine/Mine.test.tsx, src/hooks/useAuthenticated.ts, src/pages/mine/index.tsx
Date: 18 Dec 2024
Developer Name: @AnujChhikara 
---
#1295 
This PR resolves a user experience issue where navigating to the "Mine" page briefly shows the text "You are not Authorized" before displaying the shimmer loader, even when the user is in the process of authentication.
<details>
https://github.com/user-attachments/assets/df234d68-7607-40c7-a395-8edffd9cbbe5
</details>
<details>
</details>
- Fix some flaky tests
=> Prevent Unauthorized Message on Mine page when load

__tests__/Unit/pages/Tasks/index.test.tsx, src/components/tasks/TasksContent.tsx, src/styles/tasks.module.scss
Date: 20/12/2024
Developer Name: Vignesh B S
---
Closes Real-Dev-Squad/website-status#1288
- Added shimmer cards to display while tasks are being fetched in dev mode.
- Added test cases to ensure correct rendering of shimmer cards when in dev mode.
<details>
<summary>Desktop UI</summary>
</details>
<details>
<summary>Mobile UI</summary>
</details>
<details>
</details>
Test case for loading state when dev flag is not passed is also added.
=> Feat: Add shimmer card in tasks page

__tests__/Unit/Components/Tasks/TaskUpdateModal.test.tsx, src/components/taskDetails/TaskUpdateModal.tsx, src/components/taskDetails/task-details.module.scss
Date: 13/01/2025
Developer Name: Aditya Zende (aditya-zende-1)
---
- Closes #1313 
Added a cross button on Task Update Modal.
<details>
https://github.com/user-attachments/assets/9e17ed54-b8d9-4f18-bf33-f49d9d9c5863
</details>
<details>
</details>
=> Fixed: Added a button to close model.
