Real-Dev-Squad/website-status

package-lock.json, package.json, src/components/challenges/active.tsx, src/components/challenges/complete.tsx, src/components/challenges/participants/index.tsx, src/components/section/active-section/index.tsx, src/components/section/completed-section/index.tsx, src/components/section/index.tsx
Changed the type description for participants and content.
=>  Specific type description for participants and content done

src/components/Layout/index.tsx, src/components/footer/footer.module.scss, src/components/footer/index.js
@whyDontI  issue #30 has been solved. Please review.
Closes #30
=> Footer added

package-lock.json, package.json, src/components/navbar/index.tsx, src/components/pullRequests/index.tsx, src/components/pullRequests/pullRequests.module.scss, src/helperFunctions/fetch.ts, src/pages/openPRs.tsx
=> added open PRs Page

src/components/Layout/Layout.module.scss, src/components/Layout/index.tsx, src/components/challenges/active.tsx, src/components/challenges/complete.tsx, src/components/challenges/details/index.tsx, src/components/challenges/participants/index.tsx, src/components/footer/footer.module.scss, src/components/footer/index.js, src/components/pullRequests/card/index.tsx, src/components/pullRequests/index.tsx, src/components/pullRequests/section/index.tsx, src/components/section/active-section/index.tsx, src/components/section/completed-section/index.tsx, src/components/section/index.tsx, src/components/tasks/card/index.tsx, src/components/tasks/section/index.tsx, src/pages/_app.tsx, src/pages/challenges.tsx, src/pages/index.tsx, src/pages/openPRs.tsx, src/pages/stale-pr.tsx, src/styles/index.scss, tsconfig.json
Closes #55 
- Updated imports to absolute imports
https://nextjs.org/docs/advanced-features/module-path-aliases
=> Absolute imports

src/hooks/useFetch.ts
Added a custom hook to make API calls called `useFetch` as given in https://github.com/Real-Dev-Squad/website-status/issues/48
=> Add useFetch custom hook

.github/workflows/continuous-integration.yml, src/components/Accordion/Accordion.module.scss, src/components/Accordion/index.tsx, src/components/tasks/card/card.module.scss, src/pages/index.tsx, src/styles/tasks.module.scss
=> Task page accordion

package.json, src/components/Accordion/Accordion.module.scss, src/pages/index.tsx, src/styles/tasks.module.scss, yarn.lock
[issue 73](https://github.com/Real-Dev-Squad/website-status/issues/73) 
PR to fix the status issue
=> Fixed issue with filtering task based on status

src/components/tasks/card/card.module.scss
Nice to meet you all - removed the black border for the tasks page - let me know if you guys want it removed for every page.
fixes #96
=> fix: removed black border for tasks page

src/pages/openPRs.tsx
=> Removed the extra round bracket

src/components/Accordion/index.tsx, src/pages/index.tsx
Keep the accordians open by default.
=> Keep the accordions open by default

src/components/Accordion/Accordion.module.scss
added horizontal margins of 10px.
=> added horizontal margins

src/styles/index.scss
changed the styling layout for the openPR and stalePR section.
=> fixed the styling of the openPR and stalePR sections

.eslintrc.json, .storybook/main.js, .storybook/preview.js, package.json, src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/index.tsx, src/components/Card/Card.stories.tsx, src/components/Card/index.tsx, yarn.lock
=> Storybook setup

README.md, src/components/tasks/card/card.module.scss
updated the font size of the elements according to Figma design.
=> updated the card elements font size

src/components/Layout/Layout.module.scss, src/components/Layout/index.tsx
Closes #74 
Handled top menu items
=> [keyboard-navigation] added semantic html tag for keyboard nagivation

src/helperFunctions/fetch.ts, src/hooks/useFetch.ts, src/pages/availability-panel.tsx
=> cancel pending requests if user navigates away from the page

next-env.d.ts, src/pages/idle-members.tsx
=> Fixing case sensitive capitalization in sorting idle members

src/components/pullRequests/index.tsx
=> Adds white space between date and string

src/components/availability-panel/drag-drop-context/index.tsx, src/pages/availability-panel.tsx
Closes #183
Before:
https://user-images.githubusercontent.com/60848927/131250660-74ecf3c0-8641-4351-842d-d8fb0a43911c.mp4
After:
https://user-images.githubusercontent.com/60848927/131250679-24307b1c-2ffe-4256-938e-a8386a77222f.mp4
=> Content should not hide while loading

src/components/tasks/card/index.tsx
=> Excluded 'UNASSIGNED' tasks from overdue highlight

src/components/constants/display-sections.js, src/components/idleMembers/card/index.tsx
Closes #151
Addressed the comments and made the requested changes
=> Dummy image added

next-env.d.ts, src/components/Layout/Layout.module.scss, src/components/Layout/index.tsx, src/components/footer/footer.module.scss, src/components/navBar/index.tsx, src/components/navBar/navBar.module.scss, src/styles/index.scss
Closes #145 
Before :
After :
(Mobile View)
(Tablet View)
(Desktop/Laptop View)
=> Added the nav bar similar to home page

src/components/constants/task-status.js, src/pages/index.tsx
=> Task category ordering

src/pages/availability-panel.tsx
=> Fix loader in availability panel

src/components/navBar/navBar.module.scss
closes #213 
Fixed the height of navbar and underline under text
=> Fix for navbar style #213

README.md, package.json, yarn.lock
=> Add https dev server commands and instructions

src/pages/index.tsx
=> Fix unwanted edit task request for unauthorized user

src/helperFunctions/getDateInString.ts
=> date issue resolved

src/components/Accordion/index.tsx, src/components/constants/key.ts
Closes https://github.com/Real-Dev-Squad/website-status/issues/309
Weird behavior when alt key is pressed to go to edit mode by the superuser
=> fix: handled keydown press for enter and space in accordian component

src/components/constants/url.js
Solution:
Added query param `state=https://status.realdevsquad.com` in Login URL
=> Fix the redirect URL after login

next.config.js
Closes [#359](https://github.com/Real-Dev-Squad/website-status/issues/359)
=> fix: resolved warning ".future"

src/pages/mine.tsx
Reverts Real-Dev-Squad/website-status#386
=> Revert "fixed mine route issue"

src/pages/mine.tsx
Reverts Real-Dev-Squad/website-status#408
=> Revert "dev to main | Mine route issue"

.env.development
=> Fix mock service worker issue

README.md, package.json
- added volta to package.json
- updated docs
=> #420 add volta to package.json

slices/apiSlice.ts, src/components/PullRequestList/index.tsx, src/components/constants/url.ts, src/context/isUserAuthorized.tsx, src/pages/active.tsx, src/pages/availability-panel.tsx, src/pages/completed.tsx, src/pages/index.tsx
Resolves #450 
- Added the value of URLs to constants
- Added the base URL values from `.env.development` file
=> remove hardcoded value of URLs

src/components/constants/messages.ts, src/pages/index.tsx
**File added :**
1. `src/components/constants/messages.ts` : This file contains the messages constants.
**Following files are modified :**
1. `src/pages/index.tsx` : In this file replace the accordion with the Tabs component.
https://user-images.githubusercontent.com/70854507/228392332-7472f313-d17a-4d48-a03a-f6ad47654480.mp4
After Murlidhar [PR ](https://github.com/Real-Dev-Squad/website-status/pull/445)is merged, test the whole flow of the index page.
Ticket link :https://github.com/Real-Dev-Squad/website-status/issues/461
=> Render tasklist in tabs

package.json
Some Dev dependencies were listed under dependencies
closes: #489
=> moved devdependencies

__tests__/Unit/Components/Tasks/Loader.test.tsx, __tests__/Unit/Components/Tasks/TaskLevelMap.test.tsx, __tests__/Unit/hooks/useKeyLongPressed.test.tsx, package.json, src/components/tasks/card/Loader.tsx, src/components/tasks/card/TaskLevelMap.tsx, src/components/tasks/card/index.tsx, yarn.lock
**Issue: #497** 
The Task Card Component was very long because of it was hard to read and test.
broke down few of the components and wrote tests for them.
No change in functionality or UI.
**Packages Added**
Have added "[@testing-library/react-hooks": "^8.0.1](https://react-hooks-testing-library.com/usage/basic-hooks)" and "[@testing-library/dom": "^9.0.1](https://www.npmjs.com/package/@testing-library/dom)", packages as the functionality were required for testing react-hooks
=> break task card into components and write tests

src/app/services/api.ts, src/app/services/tasksApi.ts, src/helperFunctions/beautifyTaskStatus.ts, src/pages/index.tsx
=> write tasks API using RTK query

src/components/navBar/index.tsx, src/components/tasks/card/TaskTagEdit.tsx, src/components/tasks/card/index.tsx, src/context/isUserAuthorized.tsx
This PR removes all unused variables in the project to ensure low linting issues
=> remove unused variables

__tests__/Utils/getLatestDate.test.ts
This PR tests the get latest date utility.
coverage report:
=> add tests for getLatestDate utility

.env.staging, package.json
Setup staging environment with appropriate build command
command added:   ` "build:staging":"cp .env.staging .env.local && next build"`
=> add a staging build command with env

__tests__/Unit/Components/ProgressForm/ProgressForm.test.tsx, src/app/services/progressesApi.ts, src/components/ProgressForm/ProgressForm.tsx
Created a progresses API in `/src/app/services` folder
Created a `mutation query`
it would call up the progress API and post the progress data
This PR closes: #564 
Tests for the feature are coming in consecutive PRs
[Screencast from 27-05-23 12:58:20 AM IST.webm](https://github.com/Real-Dev-Squad/website-status/assets/57758447/167c3584-e3b9-4eed-ad1e-f108e79eb789)
=> Add RTK query and make task progress form work

src/styles/tasks.module.scss
-  #611
https://github.com/Real-Dev-Squad/website-status/assets/107163260/77d0e3fb-78e7-4a07-b410-93bf59392a60
https://github.com/Real-Dev-Squad/website-status/assets/107163260/35197ff3-a733-4fd6-aab9-2859a9be177c
=> Fix task content tab responsiveness

__tests__/Unit/Components/Loader/Loader.test.tsx, __tests__/Unit/Components/Tasks/Card.test.tsx, __tests__/Unit/Components/Tasks/ConditionalLinkWrapper.test.tsx, __tests__/Unit/Components/Tasks/TaskLevelMap.test.tsx, src/components/Layout/index.tsx, src/components/Loaders/Loader.module.scss, src/components/Loaders/Loader.tsx, src/components/ProgressForm/ProgressForm.tsx, src/components/navBar/index.tsx, src/components/tasks/Card/ConditionalLinkWrapper.tsx, src/components/tasks/Card/TaskLevelMap.tsx, src/components/tasks/Card/TaskTagEdit.tsx, src/components/tasks/Card/card.module.scss, src/components/tasks/Card/index.tsx, src/components/tasks/TaskList/TaskList.tsx, src/pages/active/index.tsx, src/pages/mine/index.tsx
based on #526 
This PR modifies the folder structure;  including the Loader component which was defined under card but was being used at various locations and Card folder name
No visible change to UI
=> refactor: Change folder structure and make loader component generic

src/components/tasks/card/card.module.scss, src/components/tasks/card/index.tsx, src/constants/task-status.js
Issue link: #481 
Provide dropdown for superuser to edit task status
=> Add drop down for superuser edit mode

__tests__/Unit/Components/Header/Header.test.tsx, src/components/Header/Header.module.scss, src/components/Header/index.tsx, src/components/Layout/Layout.module.scss, src/components/Layout/index.tsx, src/components/taskDetails/index.tsx, src/constants/header-categories.ts, src/interfaces/HeaderItem.type.ts, src/interfaces/taskDetails.type.ts
There was no footer on the task details page.
The task details page was missing the footer because the proper Layout was not being used.
Moved the Header code to a separate component.
Fixes #614 
N.A
Before
After
https://github.com/Real-Dev-Squad/website-status/assets/27444637/c39cdc39-e17d-4e6d-aec3-90abd1e6badc
=> added footer to task details page

__tests__/Unit/Components/Tasks/TaskStatusEditMode.test.tsx, package.json, src/components/tasks/card/TaskStatusEditMode.tsx, src/components/tasks/card/index.tsx
Issues ticket: #639 
Added test for status dropdown
Refactored code of TaskStatusEditMode component
Closes issue: #639
=> Add test and refactor code

src/components/Header/Header.module.scss, src/components/Tabs/Tabs.module.scss, src/components/tasks/TaskList/TaskList.tsx, src/components/tasks/card/card.module.scss, src/styles/tasks.module.scss
Fixed the inconsistency in the width of task-tabs and task-cards.
https://github.com/Real-Dev-Squad/website-status/assets/53934353/e3ac9266-c47e-4e77-9056-3ea3254e00a6
=> Fix : inconsistency in the width of task-tabs and task-cards

jest.config.js
closes #664 
This PR removes the config files or files that are not related to development from jest coverage by adding ignore patterns in jest config.
&nbsp;<details><summary>show table</summary>
File                                             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                             
-------------------------------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------
All files                                        |   38.34 |    27.85 |   36.38 |   38.79 |                                                                                               
app …
=> fix: Remove config folder/files from coverage report

__mocks__/handlers.ts, __mocks__/handlers/task-details.handler.ts, __tests__/Unit/hooks/taskDetailsApi.test.tsx, src/app/services/taskDetailsApi.ts, src/components/taskDetails/TaskDependencyList.tsx, src/components/taskDetails/index.tsx
close #601 
Added a Hook to return  task title with its Id
No changes as only migrate fetch call to RTK Query
No
=> Migrate fetch call of task dependsOn to RTK query

__mocks__/db/prs.ts, __mocks__/handlers.ts, __mocks__/handlers/pull-requests.handler.ts, __tests__/Unit/hooks/pullRequestsApi.test.tsx, src/app/services/pullRequestsApi.ts
Migration of Pull request API to RTK Query #676 
create a pull request API using rtk query and write its tests
Test Coverage
=> add rtk query for open prs api

__tests__/Unit/Functions/updateTasksStatus.test.ts, src/helperFunctions/updateTasksStatus.ts
For fixing the below issue we need to refactor this code.
Refactoring `src/helperFunctions/updateTasksStatus.ts` file.
=> REFACTOR : refactor updateTaskStatus

src/components/tasks/card/index.tsx
Replaced hardcoded value from handleChange function with event.target.innerHTML, so that value can be changed with whatever is in input box.
=> fixed editing of title field

src/components/tasks/card/ProgressBar.tsx, src/components/tasks/card/index.tsx
###Close #708 
Adding the Progress Slider feature behind the feature flag
#626 Parent PR
https://github.com/Real-Dev-Squad/website-status/assets/82165483/1bdc9f64-7d9c-4841-9020-76335fcbfb01
Tests will be added in this PR
https://github.com/Real-Dev-Squad/website-status/pull/686
=> Adding Progress slider feature behind feature flag

src/components/tasks/card/ProgressBar.tsx, src/components/tasks/card/index.tsx, src/hooks/useAuthenticated.ts, yarn.lock
=> Dev to main sync

src/components/tasks/card/index.tsx, src/constants/FeatureFlags.ts
Cleanup the old card design
just a cleanup PR, doesn't need test update
=> chore: cleanup old card design

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, __tests__/Utils/getDateFromTimestamp.test.ts, src/components/taskDetails/index.tsx, src/types/standup.type.ts, src/utils/getDateFromTimestamp.ts, src/utils/getTimeFromTimestamp.ts
This pull request aims to enhance the user experience by adding a new "Task Progress" section to the existing task details page. The new section will provide a unified place for users to monitor and track the progress of each task. This addition will significantly improve the user's ability to keep track of their tasks efficiently and will serve as a one-stop destination for viewing task-related information.
1. **Enhanced Task Monitoring:** With the inclusion of the "Task Progress" section, users can now easily view the progress of each task without navigating to different pages or interfaces. This streamlined approach ensures a more intuitive and seamless experience for monitoring tasks.
2. **Centralized Information:** The new section will act as a central hub where users can quickly …
=> Add Task Progress Section to Task Details Page

__tests__/Unit/Components/Select/Select.test.tsx, __tests__/Unit/Components/Tasks/TasksContent.test.tsx, src/components/Select/index.tsx
https://github.com/Real-Dev-Squad/website-status/issues/760
Touch click was not working in select, fixed it 
------------------------------
=> [760-add-dropdown]: patch fix for touch click

__mocks__/handlers/task-details.handler.ts, __tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/Details.tsx, src/components/taskDetails/index.tsx, src/interfaces/taskDetails.type.ts
This is the first level of refactoring for my task https://github.com/Real-Dev-Squad/website-status/issues/766
Just refactor this for my task and remove unnecessary  code
=> Refactor taskDetails Component

__tests__/Unit/hooks/useIntersection.ts.test.tsx, src/components/tasks/TasksContent.tsx, src/hooks/useIntersection.ts
In this PR we refactor the Intersection Observer custom hook.
=> REFACTOR: refactor useIntersection hook

__tests__/Unit/Components/Select/Select.test.tsx, src/components/Select/index.tsx
https://github.com/Real-Dev-Squad/website-status/issues/784
Used  onTouchStart instead of onPointerEnter for better UX in Select component
https://github.com/Real-Dev-Squad/website-status/assets/70846516/18bf5ed7-ed0a-465a-8986-09a41f72803d
None
=> 784 select improvement

src/components/Layout/Layout.module.scss, src/components/navBar/navBar.module.scss, src/components/taskDetails/task-details.module.scss
Fixed CSS of the task details page and made it responsive for mobile.
https://github.com/Real-Dev-Squad/website-status/assets/85179394/f3e57416-7618-4c76-90db-528303ad4a8c
=> Fixed css in mobile view of task details page

src/components/Select/index.tsx, src/components/tasks/TasksContent.tsx
[798](https://github.com/Real-Dev-Squad/website-status/issues/798)
Scroll was not working in select component fixed it
https://github.com/Real-Dev-Squad/website-status/assets/70846516/acbcf533-3622-4da9-b4d3-77bb93fd3030
=> 798-fix-select-scroll

src/components/issues/Card.module.scss, src/components/issues/Card.tsx
This pull request introduces a significant enhancement to the issues page. Currently, when searching for issues, the issues card displays the action button alongside the heading. However, to pave the way for future improvements, this PR introduces a dedicated section for the action button.
1. Created a new section within the issues card specifically for the action button.
2. Updated the styling and layout to accommodate this new design element.
3. Adjusted the underlying code to seamlessly integrate the new section.
By implementing this change, we're preparing the groundwork for a more advanced feature. In the near future, this new button section will host a form that allows super users to quickly assign tasks directly from the issues page. This streamlined process will enhance efficiency …
=> Enhancement: Improved Issues Page - Separate Action Button Section

__tests__/Unit/pages/Progress/ProgressUpdatesPage.test.tsx, src/components/ProgressForm/ProgressForm.tsx, src/components/navBar/index.tsx
=> fixed sign in button not showing when logged out

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/index.tsx, src/components/taskDetails/task-details.module.scss
- Fix the button UI and put "Request Task" behind the feature flag.
No
=> REFACTOR : Fix  Button UI

__mocks__/handlers/tasks.handler.js, __tests__/Unit/Components/Tasks/TasksContent.test.tsx, __tests__/Unit/hooks/tasksApi.test.tsx, __tests__/Unit/utils/getActiveTab.test.ts, __tests__/Utils/taskQueryParams.test.ts, src/app/services/tasksApi.ts, src/components/taskDetails/taskDependency/index.tsx, src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TaskSearch/tasksearch.module.scss, src/components/tasks/TasksContent.tsx, src/interfaces/task.type.ts, src/utils/getActiveTab.ts, src/utils/taskQueryParams.ts
Added functionality to search tasks by assignee and title.
none
https://github.com/Real-Dev-Squad/website-status/assets/70854507/3359c392-580e-4e96-acf2-2e8470cfc220
=> FEATURE : Filter tasks by  user and title

src/components/tasks/TaskSearch/TaskSearch.tsx
=> FIX : Placeholder text of search bar

__mocks__/handlers/tasks.handler.js, __tests__/Unit/Components/Tasks/TasksContent.test.tsx, __tests__/Unit/hooks/tasksApi.test.tsx, __tests__/Unit/utils/getActiveTab.test.ts, __tests__/Utils/taskQueryParams.test.ts, src/app/services/tasksApi.ts, src/components/taskDetails/taskDependency/index.tsx, src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TaskSearch/tasksearch.module.scss, src/components/tasks/TasksContent.tsx, src/interfaces/task.type.ts, src/utils/getActiveTab.ts, src/utils/taskQueryParams.ts
**Developer Name:** @sahsisunny ,
**PR Number(s):-** 
- #828 
- #833 
**Issue Ticket Number:-** 
- #782 
**Backend changes**
**Frontend Changes**
**Database changes**
**Breaking changes (If your feature is breaking/missing something please mention pending tickets)**
**Deployment notes(Any special instructions for the deployment)**
**Tested in staging**
**List of PRs going in this Sync.** 
**Feature:** 
#828 
https://github.com/Real-Dev-Squad/website-status/assets/70854507/55b2ce68-a87d-4f39-9c0d-65b73b0fd891
=> Sync dev to main

src/components/tasks/TaskSearch/tasksearch.module.scss, src/components/tasks/TasksContent.tsx
=> RELEASE : Remove FF from search bar

__tests__/Unit/Components/Tasks/ProgressBar.test.tsx, src/components/tasks/card/card.module.scss, src/components/tasks/card/progressContainer/ProgressBar.tsx, src/components/tasks/card/progressContainer/ProgressText.tsx, src/components/tasks/card/progressContainer/index.tsx
- Closes #805 
1. should update the percentage on sending requests to the backend
2. only the super user and assignee can see the update button/ save button
3. fix the CSS of the progress slider
**When logged-in user does not have super user access**
https://github.com/Real-Dev-Squad/website-status/assets/82165483/ff20e10c-d53b-4244-a5ec-23fc208f470c
**When logged-in user have super user access**
https://github.com/Real-Dev-Squad/website-status/assets/82165483/b0e40aca-c678-48ef-a22b-ad997456c9a4
- #826
**Testing PR**
- #830
=> [FIX] - Progress Slider

__tests__/Unit/Components/Tasks/TasksContent.test.tsx, src/components/tasks/TasksContent.tsx, src/pages/tasks/index.tsx
In this PR, I addressed the following changes:
https://github.com/Real-Dev-Squad/website-status/assets/70854507/e335937b-d1d3-4489-8fe2-4b13dea57521
=> FIX : fix url param for task search

__mocks__/handlers/users.handler.js, __tests__/Unit/Components/Tasks/Card.test.tsx, __tests__/Unit/Components/Tasks/Suggestions.test.tsx, src/app/services/usersApi.ts, src/components/tasks/SuggestionBox/Suggestions.tsx, src/components/tasks/card/index.tsx, src/interfaces/suggestionBox.type.ts
migrated the fetch call to rtk query, wrote new tests, refactored the component
test coverage:
=> Suggestions Component Test & Refactoring Code

__tests__/Unit/Components/Issues/ActionForm.test.tsx, src/components/issues/ActionForm.tsx, src/components/issues/Card.tsx
**Issue:** #851 
**Changes Made:**
- Implemented toast messages for task assignment to provide clear feedback to users (success or error) during the assignment process.
- Set a default status for tasks when they are assigned to streamline the task management workflow.
- Introduced a loader to indicate the loading state during task assignment.
**Testing Done:**
- Tested the changes thoroughly to ensure that toast messages appear correctly for assignment feedback.
- Verified that tasks are assigned with the default status as expected.
- Checked the loader functionality to indicate the loading state during assignment.
**Visuals:**
https://github.com/Real-Dev-Squad/website-status/assets/57758447/86b153b7-fef6-49cc-8a7f-28d1898c45ac
**Related Issues:**
Closes #851
=> Enhance Task Assignment UX: Toast Messages, Default Status, and Loader

__tests__/Unit/Components/Issues/ActionForm.test.tsx, src/components/issues/ActionForm.tsx, src/components/issues/Card.module.scss
Add suggestion box to input form.
=> add suggestion box to action form

__tests__/Unit/Components/Tasks/Card.test.tsx, __tests__/Unit/Components/Tasks/TaskStatusEditMode.test.tsx, src/components/tasks/card/TaskStatusEditMode.tsx, src/components/tasks/card/index.tsx
https://github.com/Real-Dev-Squad/website-status/assets/30263070/ba65a352-e8c2-48b2-bc2a-3d7dad6db3d6
=> removed feature flag

__tests__/Unit/Components/Tasks/SuggestionList.test.tsx, __tests__/Unit/Components/Tasks/Suggestions.test.tsx
=> Tests for i888 keyboard accessablity

__tests__/Unit/Components/Tasks/SuggestionList.test.tsx, __tests__/Unit/Components/Tasks/Suggestions.test.tsx, src/components/issues/ActionForm.tsx, src/components/issues/Card.module.scss, src/components/tasks/SuggestionBox/SuggestionBox.tsx, src/components/tasks/SuggestionBox/SuggestionList.tsx, src/components/tasks/SuggestionBox/Suggestions.tsx, src/components/tasks/SuggestionBox/suggestion.module.scss, src/components/tasks/card/index.tsx, src/interfaces/suggestionBox.type.ts
#888 
Add keyboard accessibility to the user suggestion box. selection of the users should happen upon hitting enter, up, and down to select
https://github.com/Real-Dev-Squad/website-status/assets/34452139/3409bd4a-5d0c-45df-9c29-a12405695bd0
Tests are in the #889
=> add keyboard navigation support

src/components/issues/Card.module.scss
Fix UI Issues inside card component of Issues Tab. 
Fixes: https://github.com/Real-Dev-Squad/website-status/issues/898
Content inside the issue card is crossing the parent div container width
Design Doc: https://docs.google.com/document/d/1BEczYqtb8onsx2dJY97y-FcVby6F6AD7uoFVbasJ1z8/edit?usp=sharing
**Before Fix**:
**After Fix**, all child elements inside card are not crossing width of root div.
*Verified in mobile/desktop both
NA
=>  Fix UI of issues tab

__tests__/Unit/Components/Issues/Card.test.tsx, src/components/issues/Card.tsx
Remove assign task form out of feature flag
Test case state:
=> Remove Feature Flag | Assign Issue

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/index.tsx
Remove update task progress out of feature flag
Test case stats:
=> Remove Feature Flag | update task progress

__tests__/Unit/Components/Issues/Card.test.tsx, src/components/issues/Card.tsx
Reverts Real-Dev-Squad/website-status#908
=> Revert "Remove Feature Flag | Assign Issue"

__tests__/Unit/Components/Navbar/Navbar.test.tsx
- fix test which are skipped in `navbar.test.tsx` file
=> fix failing test of navbar

src/components/tasks/card/card.module.scss, src/components/tasks/card/index.tsx
- Dev to main sync up issue due to merge conflicts
- Need to Resolve conflicts between the main and working branch (issue-928-fix)
- For [this PR](https://github.com/Real-Dev-Squad/website-status/pull/926)
=> Resolve merge conflicts between main and working branch issue-928-fix

src/components/tasks/card/card.module.scss
=> hotfix to prod

src/components/tasks/card/card.module.scss
Reverts Real-Dev-Squad/website-status#940
=> Revert "hotfix to prod"

src/components/tasks/card/card.module.scss
Reverts Real-Dev-Squad/website-status#941
=> Revert "fix css of card module"

src/components/PullRequestList/PullRequestList.module.scss, src/pages/mine/index.tsx, src/styles/tasks.module.scss
**Date:** 21th Nov 2023
**Developer Name:** @ajoykumardas12
**PR Number(s):**
- #1010 
**Issue Ticket Number:**
- #999 
Frontend Changes
Database changes
Breaking changes (If your feature is breaking/missing something please mention pending tickets)
Tested in staging
**Before:**
**After:**
=> Dev to Main Sync 

__tests__/Unit/Components/Tabs/Tab.test.tsx, __tests__/Unit/Components/Tasks/TasksContent.test.tsx, __tests__/Unit/utils/getActiveTab.test.ts, src/components/tasks/TasksContent.tsx, src/constants/constants.ts, src/constants/tasks.ts, src/interfaces/task.type.ts, src/utils/getActiveTab.ts, src/utils/getChangedStatusName.ts
Reverts Real-Dev-Squad/website-status#1011
Reason: removing feature flag without running 1 time script break things on prod
=> Revert "Remove Feature Flag: Task Tab and COMPLETED Task Status Removal"

src/components/tasks/TaskSearch/tasksearch.module.scss
1. Filter modal was not responsive in dev mode
NA
https://github.com/Real-Dev-Squad/website-status/assets/56365512/547ceae0-3159-4a31-ac9d-cd0ced657f30
=> Style : Fixed responsiveness of filter modal

__tests__/Unit/Components/Tasks/TaskSearch.test.tsx, src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TaskSearch/tasksearch.module.scss, src/components/tasks/TasksContent.tsx, src/components/tasks/card/card.module.scss, src/utils/generateSuggestions.ts
- https://github.com/Real-Dev-Squad/website-status/pull/1036
- https://github.com/Real-Dev-Squad/website-status/pull/1035
Will enable tests once these PRs gets merged
- https://github.com/Real-Dev-Squad/website-status/pull/1036
- https://github.com/Real-Dev-Squad/website-status/pull/1036
1. Updated helper to generate sentences based on provided parameters
2. Added a component to display suggestions, if found, otherwise show `no suggestion found`
3. Display selected options as pills
4. Pills can be editable/deletable
5. All the features should follow web accessibility standards (accessible through the keyboard as well)
1. Should render suggestion if typed input has more than 2 characters and has no key
2.  Should render suggestion if typed input has more than 2 characters in value if key …
=> Feat : Added task search functionality

src/components/tasks/TaskSearch/Suggestion/pill.module.scss
1. Enabled `cursor:pointer` on delete button
NA
NA
=> Style : Added pointer type cursor on delete button

__tests__/Unit/Components/Tasks/Options.test.tsx, __tests__/Unit/Components/Tasks/TaskSearch.test.tsx, src/components/tasks/TaskSearch/Suggestion/Option.tsx, src/components/tasks/TaskSearch/Suggestion/Options.tsx, src/components/tasks/TaskSearch/Suggestion/Pill.tsx, src/components/tasks/TaskSearch/Suggestion/option.module.scss, src/components/tasks/TaskSearch/Suggestion/pill.module.scss, src/components/tasks/TaskSearch/TaskSearch.tsx, src/components/tasks/TaskSearch/tasksearch.module.scss, src/helperFunctions/findCoordinates.ts
1. Show suggestions just like Google search does.
2. Suggestions position should persist even if text changes or screen size changes
3. Fixed change in height of search field just before deleting the pill
4. Minor UI-related fixes
5. Selected 0th index suggestion by default if available
https://github.com/Real-Dev-Squad/website-status/assets/56365512/a5e0bc6b-aca5-446f-9a5c-638f66a103a8
https://github.com/Real-Dev-Squad/website-status/assets/56365512/fb562d8e-ec9f-4c64-b641-0f611ddd4605
=> UI Improvements

__tests__/Utils/updateQueryStringToUrl.test.ts, src/components/Layout/index.tsx, src/components/ProgressForm/ProgressForm.tsx, src/components/issues/ActionForm.tsx, src/components/issues/Card.tsx, src/components/navBar/index.tsx, src/components/taskDetails/index.tsx, src/components/tasks/card/TaskStatusEditMode.tsx, src/components/tasks/card/index.tsx, src/components/tasks/card/progressContainer/ProgressBar.tsx, src/interfaces/taskDetails.type.ts
=> remove some warnings like removed unused var

__tests__/Unit/Components/Calendar/UserSearchField.test.tsx, package.json, src/app/services/usersApi.ts, src/components/Calendar/UserSearchField.module.scss, src/components/Calendar/UserSearchField.tsx, src/constants/calendar.ts, src/constants/header-categories.ts, src/hooks/useOutsideAlerter.ts, src/pages/_app.tsx, src/pages/calendar/index.tsx, src/styles/calendar.scss, src/utils/userStatusCalendar.ts, yarn.lock
Date: 01/02/2024
Developer Name: @lakshayman 
---
Closes #1089 
<details>
</details>
Test coverage screenshots are not necessary as PR for the test will be raised by another dev.
=> User Status Calendar

.github/workflows/continuous-integration.yml
Date: 31th Jan 2024
Developer Name: @ajoykumardas12 
---
closes #1099 
Updated Github workflows to run on all branches. Related Docs: [Link](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags)
Previously branches which had `/` in name were ignored from workflows. eg, #1098 
- Upgraded actions/checkout to v3 as v2 is being deprecated. Also upgraded actions/setup-node to v3.
No visual change.
This PR doesn't affect tests on dev, affects tests on Github CI.
=> Run Github Workflows On All Branches

.github/workflows/continuous-integration.yml
Date: 06/02/2024
Developer Name: Tejas 
---
#1105 
This PR consist of test cases written for three utils funtion of calendar that is getStartOfDay, getDatesInRange, processData.
- [] No
NA
| File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
|----------------------------|---------|----------|---------|---------|-------------------|
| userStatusCalendar.ts       | 63.33   | 80       | 57.14   | 62.06   | 31, 52-69          |
- **Test Suites:** 1 failed, 100 passed, 101 total
- **Tests:** 452 passed, 452 total
- **Snapshots:** 0 total
- **Time:** 59.632 s
1. **Valid Dates:** Verifies if the function correctly returns the start of the day for valid dates.
2. **Middle Time:** Checks if the function handles dates with middle time correctly.
3. **End of …
=> Utils test/calendar

.env.development, src/components/common/Tooltip/Tooltip.tsx, src/components/common/Tooltip/tooltip.module.scss, src/components/taskDetails/ProgressDetails.tsx, src/components/taskDetails/ProgressUpdateCard/LatestProgressUpdateCardPresentation.tsx, src/components/taskDetails/ProgressUpdateCard/ProgressUpdateCard.tsx, src/components/taskDetails/ProgressUpdateCard/ProgressUpdateCardPresentation.tsx, src/components/taskDetails/ProgressUpdateCard/latest-progress-update-card.module.scss, src/components/taskDetails/ProgressUpdateCard/progress-update-card.module.scss, src/components/taskDetails/ProgressUpdateCard/progressUpdateCard.types.ts
Date: 09-02-2024
Developer Name: Satyam Bajpai
---
- #1076 
In this PR I have added progress update card to expand and shrink on click. When in expand mode a user can see every content of the progress update i.e
- Completed
- Planned
- Blocker
Tests PR for this PR is here at,
- #1112
>Note: Tests are to handled separately, please review this one and I will reference test in this one and then only merge both feature and tests PR.
> Desktop View
> Tab View
> Mobile view
<details>
</details>
=> feat: add expand feature in progress update card component on click

src/components/taskDetails/ProgressUpdateCard/progress-update-card.module.scss
Date: 16-02-2024
Developer Name: Satyam Bajpai
---
It's a fix PR for the issue found in dev to main PR,
- https://github.com/Real-Dev-Squad/website-status/pull/1117
> Before
> After
No test changes
=> styles: fix border separator issue

__tests__/Unit/Components/Issues/TaskRequestForm.test.tsx, __tests__/Unit/Components/Tasks/ProgressUpdateCard/ProgressUpdateCardPresentation.test.tsx, __tests__/Unit/Components/Tooltip/Tooltip.test.tsx, src/components/common/Tooltip/Tooltip.tsx, src/components/common/Tooltip/tooltip.module.scss, src/components/taskDetails/ProgressDetails.tsx, src/components/taskDetails/ProgressUpdateCard/LatestProgressUpdateCardPresentation.tsx, src/components/taskDetails/ProgressUpdateCard/ProgressUpdateCard.tsx, src/components/taskDetails/ProgressUpdateCard/ProgressUpdateCardPresentation.tsx, src/components/taskDetails/ProgressUpdateCard/latest-progress-update-card.module.scss, src/components/taskDetails/ProgressUpdateCard/progress-update-card.module.scss, src/components/taskDetails/ProgressUpdateCard/progressUpdateCard.types.ts
Date: 15-02-2024
Developer Name: Satyam Bajpai
---
- #1109
- #1112
- #1118
https://github.com/Real-Dev-Squad/website-status/assets/85296770/35e96b9b-7d42-4f91-95f2-527ad484f3c5
> Staging Proof
<details>
</details>
=> SYNC: dev to main

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/index.tsx
Date: 17-02-2024
Developer Name: Pavan Bhat
---
Closes #1126 
We have removed tcr cta on the task details page as the task details page is accessed when we already have the task and tcr cta would not be useful having it here
<details>
</details>
<details>
Same as before
</details>
=> Removed Request for task button on task details page

src/components/taskDetails/task-details.module.scss
Date: 17-2-2024
Developer Name: Vishal Kr Kamat
---
Closes: #1128 
<details>
</details>
</details>
=> Font style fix

src/helperFunctions/convertTimeStamp.ts
Date: 17 February 2024
---
https://github.com/Real-Dev-Squad/website-status/issues/1129
Enhanced the TaskDetails component to display dates and times in a more human-readable format. This improvement enhances user readability and experience by presenting dates and times more clearly and intuitively.
<details>
[Screencast from 18-02-24 12:06:45 AM IST.webm](https://github.com/Real-Dev-Squad/website-status/assets/55826451/e3e2e8b4-b884-4dc6-8cf3-4dbeecb1ce08)
</details>
<details>
</details>
=> Feature: Implement human-readable date and time format in TaskDetails component

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/Details.tsx
Date: 19/02/2024
Developer Name: Palak Gupta (palakgupta2712)
---
Closes #1140 
1. Removal of feature flag from extension req button if any extension request is pending for that task.
2. Also, opening the extension request link in new tab, once clicked on the icon.
With feature flag:- 
After removal of feature flag:-
<details>
</details>
=> #1140: removal of feature flag from task detail page

src/components/taskDetails/index.tsx, src/components/tasks/card/card.module.scss, src/components/tasks/card/index.tsx, src/components/tasks/card/progressContainer/ProgressBar.tsx, src/components/tasks/card/progressContainer/index.tsx
Date: 29 feb, 2024
Developer Name: Tejas
---
#1107 
- In this issue, there is a sliding Progress Bar so that the super user and the assignee user can update his/her task, this task was under the dev flag which needs to be brought into production.
- But while working there was some UI issue, which has also been covered in this PR, please check the video for more information.
In this feature firstly the process has been removed from DevFeature and now every person can view the progress of any task, on top of that, the Superuser and assignee user.
- Now the UI is not breaking, please check in the video.
I will add a video soon. Not able to upload it now.
https://github.com/Real-Dev-Squad/website-status/assets/98630752/04a6189f-41b2-40bc-9fac-323efdb62c99 …
=> feat:remove progressContainer from dev=true feature flag

src/components/tasks/TaskSearchDev/TaskSearchDev.tsx
NA
On removing selected filter, the task list is not refreshed. 
<details>
</details>
<details>
</details>
=> [Hot Fix] Fix filter delete functionality

__tests__/Utils/generateSuggestions.test.ts, src/components/tasks/TaskSearchDev/useFilterSuggestion.tsx, src/utils/generateSuggestions.ts
- #1170
<details>
<summary>Screenshot Old</summary>
</details>
<details>
<summary>Screenshot New </summary>
</details>
<details>
</details>
=> fix bugs of assignee search

src/components/ProgressForm/ProgressForm.tsx
Date: 29 feb, 2024
Developer Name: Atif
---
Closes: #1158 
Add .trim() to the values obtained from the textareas before submitting.
<details>
https://github.com/Real-Dev-Squad/website-status/assets/51026543/96615d49-ff56-4ed2-80a3-cc7030de57bd
</details>
<details>
</details>
=> fix : textareas must not have leading or trailing white space on progress update form

__tests__/Unit/Components/Issues/TaskRequestForm.test.tsx, src/app/services/taskRequestApi.ts, src/components/MarkDownEditor/MarkDownEditor.tsx, src/components/issues/Card.module.scss, src/components/issues/Card.tsx, src/components/issues/TaskManagementModal.tsx, src/components/issues/TaskRequestForm.tsx, src/constants/FeatureFlags.ts
Date: 8th March 2024
---
#1162 
Replace the textbox with markdown and preview creating TCR
Will update
<details>
</details>
<details>
</details>
=> Add markdown editor with preview option for creating TCR

src/components/issues/Card.tsx, src/components/issues/TaskManagementModal.tsx, src/constants/FeatureFlags.ts
Date: 24th March 2024
Remove feature flag and use dev in query param
---
<details>
</details>
<details>
</details>
=> Use dev instead of Feature Flag

__tests__/Unit/Components/Issues/TaskRequestForm.test.tsx, src/components/MarkDownEditor/MarkDownEditor.tsx
Date: 24th March 2024
Add additional tests
---
<details>
</details>
<details>
</details>
=> Add tests to ensure markdown is rendered correctly

src/app/services/taskRequestApi.ts, src/components/issues/Card.tsx
Date: 26th March 2024 
---
Closes no issue, restores feature flag
restores feature flag
<details>
</details>
<details>
</details>
=> Restore feature flag

__tests__/Unit/Components/Issues/TaskRequestForm.test.tsx, src/components/issues/Card.tsx, src/components/issues/TaskManagementModal.tsx, src/components/issues/TaskRequestForm.tsx
Date: 18th April 2024
---
Drop Feature Flag for markdown support in TCR
<details>
</details>
<details>
</details>
=> Drop feature flag for markdown support in TCR description

src/app/services/tasksApi.ts, src/components/tasks/TasksContent.tsx, src/interfaces/task.type.ts
Date: May 21 2024
Developer Name: @skv93-coder 
---
https://github.com/Real-Dev-Squad/website-status/issues/1197
Added dev flag in fetch tasks API, so now the same param can fetch DONE and COMPLETED required for backward compatibilty.
<details>
</details>
<details>
</details>
No test cases are written as this PR only adds dev flag
=> Add dev flag in fetch task api so done and completed status can be fetched simulatenously

src/components/taskDetails/Details.tsx
Date: `May 28 2024`
Developer Name: `Achintya`
---
Closes #1209 
Instead of `Started On` with the original date and time, I changed it to `Started` with relative dates and when hovering over that filed users would see the original date and time on the tooltip, same with the `Ends On`
<details>
[Screencast from 28-05-24 12:55:41 AM IST.webm](https://github.com/Real-Dev-Squad/website-status/assets/55826451/d2613638-fb1c-494f-b238-1ca78da6e49f)
</details>
<details>
</details>
=> Remove Feature flag from task details page

__tests__/Unit/Components/Tasks/ProgressUpdateCard/LatestProgressUpdateCard.test.tsx, __tests__/Unit/Components/Tasks/ProgressUpdateCard/ProgressUpdateCard.test.tsx, src/components/taskDetails/Details.tsx, src/components/taskDetails/ProgressUpdateCard/LatestProgressUpdateCard.tsx, src/components/taskDetails/ProgressUpdateCard/ProgressUpdateCard.tsx
Date: 15th June 2024
---
closes #1208 
This pull request standardizes the date format on the status site task details page in two sections, one in Started Ended and another in the Progress details section. The tooltip for the date has been updated to a consistent format, ensuring better readability and uniformity across the application.
<details>
<summary>Screenrecording of task details page</summary>
[Screencast from 18-06-24 12:40:53 AM IST.webm](https://github.com/Real-Dev-Squad/website-status/assets/55826451/a104484a-2462-404b-b26a-8c2fbe67d5c8)
</details>
<details>
</details>
=> Feature: Standardization of date format of status site task details page

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/taskDetails/index.tsx, src/components/taskDetails/task-details.module.scss, src/components/tasks/SuggestionBox/suggestion.module.scss
Date: 31 July, 2024
---
- Closes #1224 
- Updates the `TaskDetails` component and its corresponding test to ensure the assignee input field appears correctly where the name is in edit mode. Also, remove the feature flag from those stable features for superusers as @ankushdharkar asked me to.
<details>
https://github.com/user-attachments/assets/6f9b9baf-448b-4cda-ba1a-8830051d9ce3
</details>
<details>
</details>
- Ensured that the feature worked as expected after removing the feature flag from different features. Also, it didn't break other features as well. I verified that the assignee input appeared (where the name is) correctly on the task details page in edit mode.
=> Fix: Assignee text box alignment

__tests__/Unit/Components/Tasks/Card.test.tsx, src/components/taskDetails/Details.tsx, src/components/taskDetails/index.tsx
Date: 20/10/2024
Developer Name: Ayush Sanj
---
Removed feature flag conditions and is safe to use in production.
Closed PR: https://github.com/Real-Dev-Squad/website-status/pull/1260
<details>
</details>
<details>
</details>
=> FF removal for PR #1260

__tests__/Unit/Components/Tasks/Card.test.tsx, __tests__/Unit/pages/Mine/Mine.test.tsx, src/pages/mine/index.tsx
Date: 21 Oct, 2024
Developer Name: @pankajjs 
---
- Closes #1276 
This PR removes dev flag to from mine page to show the new UI changes.
<details>
<summary>Working Video</summary>
https://github.com/user-attachments/assets/21aaa51b-3715-4de9-b805-6d7808b8cda5
</details>
<details>
<summary>Screenshots</summary>
</details>
=> Remove dev flag to show the new UI changes

__tests__/Unit/Components/ProgressForm/inputWithQuestions.test.tsx, __tests__/Unit/Components/Tasks/ProgressBar.test.tsx, __tests__/Unit/Components/Tasks/ProgressIndicator.test.tsx, __tests__/Unit/Components/Tasks/ProgressSlider.test.tsx, __tests__/Unit/Components/Tasks/ProgressText.test.tsx, __tests__/Unit/Components/Tasks/TaskDetails.test.tsx, __tests__/Unit/Components/Tasks/TaskUpdateModal.test.tsx, __tests__/Unit/pages/Progress/ProgressUpdatesPage.test.tsx
Date: `3rd December, 2024`
---
- Closes #1274
- Test cases for progress update modal
<details>
</details>
<details>
</details>
=> Test: progress update flow modal

__tests__/Unit/Components/Tasks/ProgressIndicator.test.tsx, src/components/ProgressForm/InputWithQuestions.tsx, src/components/ProgressForm/ProgressForm.tsx, src/components/taskDetails/TaskUpdateModal.tsx, src/components/taskDetails/index.tsx, src/components/tasks/card/progressContainer/ProgressIndicator.tsx, src/components/tasks/card/progressContainer/ProgressSlider.tsx, src/components/tasks/card/progressContainer/ProgressText.tsx, src/components/tasks/card/progressContainer/index.tsx
Date: `December 19, 2024`
---
- Remove feature flag `?dev=true` from the new progress update flow modal.
<details>
https://github.com/user-attachments/assets/897cc80c-4455-49ad-a1cd-e6cdd7ee50a4
</details>
<details>
</details>
=> chore: remove feature flag from the new progress update flow modal

__tests__/Unit/Components/Tasks/ProgressSlider.test.tsx, src/components/tasks/card/progressContainer/ProgressSlider.tsx
Date: 25 Dec 2024
Developer Name: @AnujChhikara 
---
- Closes #1286 
This PR fixes an issue where the ProgressSlider component was not working on mobile devices.
<details>
</details>
<details>
</details>
=> fix: updating progress slider from mobile

__tests__/Unit/pages/Tasks/index.test.tsx, src/components/tasks/TasksContent.tsx
Date: 13 Jan 2025
Developer Name: Vignesh
---
- Remove feature flag ?dev=true from the tasks page shimmer card feature.
<details>
</details>
<details>
</details>
=> chore: Remove feature flag for shimmer card addition in tasks page.

__tests__/Unit/Components/Tasks/TaskDetails.test.tsx, src/components/Loaders/taskDetailsShimmer/index.tsx, src/components/Loaders/taskDetailsShimmer/taskDetailsShimmer.module.scss, src/components/taskDetails/index.tsx, src/components/taskDetails/task-details.module.scss
Date: 25 Jan
Developer Name:  Ashutosh Sahoo
---
- Closes #1303 
This PR is raised to add a shimmer effect to the Task detail page
<details>
</details>
<details>
</details>
=> feat: add shimmer effect in the task details page

__mocks__/db/extensionRequests.ts, __tests__/Unit/Components/ExtensionRequest/ExtensionRequestForm.test.tsx, __tests__/Unit/Components/ExtensionRequest/ExtensionStatusModal.test.tsx, src/app/services/tasksApi.ts, src/components/ExtensionRequest/ExtensionRequestForm.tsx, src/components/ExtensionRequest/ExtensionStatusModal.tsx, src/components/ExtensionRequest/Form.module.scss, src/components/tasks/card/index.tsx, src/constants/constants.ts, src/interfaces/task.type.ts
Date: 29-05-2025
Developer Name: Rishi Chaubey
---
- closes #1263 
- This PR contains the extension request form component which we utilise while filling up the extension request details
- Here are the test concerning this PR #1356 
<details>
https://github.com/user-attachments/assets/125f0633-60ea-47d2-9113-0d7be2fbc6ce
</details>
<details>
</details>
=> [My Site Migration] Integration Extension Request Form to status site
